import { notFound } from 'next/navigation';
import Image from 'next/image';
import { demoGallery } from '@/lib/deliveries/demo';
import { PropertyExperience } from '@/components/marketing/PropertyExperience';
import { toEmbedUrl } from '@/lib/deliverables/embed';
import type { Metadata } from 'next';
import { loadProperty } from '@/lib/marketing/load-property';
export const dynamic='force-dynamic';
export async function generateMetadata({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{preview?:string;unbranded?:string}>}):Promise<Metadata>{
 const {slug}=await params;const search=await searchParams;const data=slug==='demo'?null:await loadProperty(slug,search.preview==='1');
 if(!data)return {title:'Property showcase',robots:{index:false,follow:false}};
 const title=data.site.headline;const description=(data.site.description||'Explore this property, photography and film.').slice(0,200);
 return {title,description,robots:{index:data.site.is_published&&search.preview!=='1',follow:data.site.is_published},openGraph:{title,description,type:'website',...(data.photos.length?{images:[`https://app.oceanoblue.net/api/property-public/${slug}/hero`]}:{})},twitter:{card:data.photos.length?'summary_large_image':'summary',title,description,...(data.photos.length?{images:[`https://app.oceanoblue.net/api/property-public/${slug}/hero`]}:{})}};
}
export default async function Page({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{preview?:string;unbranded?:string}>}) {
 const {slug}=await params;const search=await searchParams;const data=slug==='demo'?{site:{is_published:true,headline:'The Coastal Collection',description:'A sample property website showcasing finished photography, property details, and a clear way to contact the listing agent.',agent_name:'Sample Coastal Realty',agent_phone:'',agent_email:'',asking_price_cents:null},listing:{...demoGallery.listing,bedrooms:null,bathrooms:null,sqft:null},photos:demoGallery.photos.map(p=>({id:p.id,url:p.url!,alt:p.filename}))}:await loadProperty(slug,search.preview==='1');if(!data)notFound();const {listing,photos}=data;const site:any=data.site;const unbranded=search.unbranded==='1';
 const facts=[listing?.bedrooms!=null?`${listing.bedrooms} bedrooms`:null,listing?.bathrooms!=null?`${listing.bathrooms} bathrooms`:null,listing?.sqft?`${listing.sqft.toLocaleString()} sq ft`:null,site.acreage!=null?`${site.acreage} acres`:null].filter(Boolean);
 return <main className="min-h-screen bg-[#f7f6f2] text-[#16313d]">{slug==='demo'&&<div className="bg-slate-100 px-6 py-3 text-center text-sm">Sample property website · Public sample photography</div>}{!site.is_published&&<div className="bg-amber-100 px-6 py-3 text-center text-sm">Draft preview — only your team can see this page.</div>}
   <header className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-6 py-6"><span className="text-sm font-semibold tracking-widest">{unbranded?'PROPERTY SHOWCASE':site.agent_name||'OCEANO BLUE MEDIA'}</span><nav className="flex gap-4 text-sm">{site.video_url&&<a href="#film" className="underline">Watch film</a>}<a href="#photos" className="underline">Photos</a>{!unbranded&&site.is_published&&slug!=='demo'&&<a href="#inquire" className="underline">Request showing</a>}</nav></header>
   {photos[0]&&<div className="relative h-[55vh] min-h-72 max-h-[720px]"><Image src={photos[0].url} alt={photos[0].alt} fill unoptimized priority className="object-cover"/></div>}
   <section className="mx-auto grid max-w-6xl gap-8 px-6 py-14 md:grid-cols-[2fr_1fr]"><div><p className="text-xs uppercase tracking-[0.2em]">{[listing?.city,listing?.state].filter(Boolean).join(', ')}</p><h1 className="mt-4 font-serif text-4xl leading-tight sm:text-6xl">{site.headline}</h1><p className="mt-5 text-lg">{listing?.address_line1}</p><p className="mt-4 text-sm text-slate-600">{facts.join(' · ')}</p>{site.highlights&&<ul className="mt-6 grid gap-3 sm:grid-cols-2">{site.highlights.split('\n').filter(Boolean).map((item:string,i:number)=><li key={i} className="rounded-lg border border-slate-200 p-4 text-sm">{item}</li>)}</ul>}{site.description&&<p className="mt-8 whitespace-pre-wrap leading-8 text-slate-700">{site.description}</p>}</div>
   <div className="space-y-6">{site.asking_price_cents!==null&&<p className="font-serif text-4xl">{new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(site.asking_price_cents/100)}</p>}{!unbranded&&(site.agent_name||site.agent_phone||site.agent_email)&&<div className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs uppercase tracking-widest">For more information</p>{site.agent_image_url&&<Image src={site.agent_image_url} alt="Listing agent" width={96} height={96} unoptimized className="mt-4 rounded-lg object-cover"/>}<p className="mt-3 text-xl">{site.agent_name}</p>{site.brokerage&&<p className="mt-2 text-sm">{site.brokerage}</p>}{site.agent_phone&&<a className="mt-4 block underline" href={`tel:${site.agent_phone.replace(/[^0-9+]/g,'')}`}>{site.agent_phone}</a>}{site.agent_email&&<a className="mt-3 block break-all underline" href={`mailto:${site.agent_email}`}>{site.agent_email}</a>}</div>}</div></section>
   <PropertyExperience slug={slug} enabled={site.is_published&&slug!=='demo'&&search.preview!=='1'} videoUrl={site.video_url||''} unbranded={unbranded}/>
   {site.social_video_urls?.length>0&&<section className="mx-auto max-w-6xl px-6 pb-14"><h2 className="mb-6 font-serif text-3xl">Property highlights on film</h2><div className="grid gap-5 sm:grid-cols-3">{site.social_video_urls.map((url:string,i:number)=>{const embed=toEmbedUrl(url);return embed?<iframe key={url} src={embed} title={`Property highlight ${i+1}`} className="aspect-[9/16] w-full rounded-xl bg-black" allowFullScreen/>:<a key={url} href={url} target="_blank" rel="noreferrer" className="underline">Watch highlight {i+1}</a>;})}</div></section>}
   <section className="mx-auto max-w-6xl px-6 pb-10"><h2 className="mb-4 font-serif text-3xl">Location</h2><p>{[listing?.address_line1,listing?.city,listing?.state,listing?.zip].filter(Boolean).join(', ')}</p><a className="mt-3 inline-block text-sm underline" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([listing?.address_line1,listing?.city,listing?.state,listing?.zip].filter(Boolean).join(', '))}`}>View on map</a></section>
   {(site.tour_url||site.floor_plan_url)&&<section className="mx-auto flex max-w-6xl flex-wrap gap-4 px-6 pb-10">{site.tour_url&&<a className="btn-secondary" href={site.tour_url} target="_blank" rel="noreferrer">Explore 3D / 360 tour</a>}{site.floor_plan_url&&<a className="btn-secondary" href={site.floor_plan_url} target="_blank" rel="noreferrer">View floor plan</a>}</section>}
   {site.mls_number&&<p className="mx-auto max-w-6xl px-6 pb-6 text-xs">MLS #{site.mls_number}</p>}
   <section id="photos" className="mx-auto max-w-6xl px-6 pb-14"><h2 className="mb-6 font-serif text-3xl">Explore the property</h2><div className="grid gap-4 sm:grid-cols-2">{photos.map((photo:any,i:number)=><a key={photo.id} data-property-photo={photo.id} className={`relative block aspect-[3/2] overflow-hidden rounded-lg ${i%5===0?'sm:col-span-2 sm:aspect-[2/1]':''}`} href={photo.url} target="_blank" rel="noreferrer"><Image src={photo.url} alt={photo.alt} fill unoptimized className="object-cover"/></a>)}</div></section>
   {!unbranded&&<footer className="border-t border-slate-200 px-6 py-8 text-center text-xs uppercase tracking-widest">Photography by Oceano Blue Media</footer>}
 </main>;
}
