'use client';
import Link from 'next/link';
import { useEffect,useRef,useState } from 'react';
import type { GalleryData } from '@/components/gallery/ClientGallery';
import { drawMarketing,templateSizes } from '@/lib/marketing/canvas';
export function MarketingStudio({token,initialData,demo=false}:{token:string;initialData?:GalleryData;demo?:boolean}) {
 const [data,setData]=useState<GalleryData|null>(initialData||null);const [selected,setSelected]=useState(initialData?.photos[0]?.id||'');const [format,setFormat]=useState<keyof typeof templateSizes>('square');
 const [label,setLabel]=useState('Just listed');const [address,setAddress]=useState(initialData?.listing?.address_line1||'');const [details,setDetails]=useState(initialData?.listing?[initialData.listing.city,initialData.listing.state].join(', '):'');const [name,setName]=useState('');const [contact,setContact]=useState('');const [error,setError]=useState('');const [image,setImage]=useState<HTMLImageElement|null>(null);const canvas=useRef<HTMLCanvasElement>(null);const [exportUrl,setExportUrl]=useState<string|null>(null);
 useEffect(()=>{if(demo)return;let active=true;fetch(`/api/delivery/${token}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error('Gallery unavailable or expired.');if(active){setData(d);setSelected(d.photos[0]?.id||'');setAddress(d.listing?.address_line1||'');setDetails(d.listing?[d.listing.city,d.listing.state].join(', '):'');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[token,demo]);
 const photo=data?.photos.find(p=>p.id===selected);const photoUrl=data?.paywall?.active?null:demo?photo?.url:photo?`/api/delivery/${token}/marketing-photo/${photo.id}`:null;
 useEffect(()=>{setImage(null);if(!photoUrl)return;let active=true;const img=new window.Image();img.onload=()=>{if(active){setImage(img);setError('');}};img.onerror=()=>{if(active)setError('This photo could not load. Refresh the gallery or choose another photo.');};img.src=photoUrl;return()=>{active=false;};},[photoUrl]);
 useEffect(()=>{setExportUrl(null);if(!canvas.current||!image)return;drawMarketing(canvas.current,image,format,{label,address,details,name,contact});let active=true;let url:string|undefined;const timer=setTimeout(()=>canvas.current?.toBlob(blob=>{if(!active)return;if(!blob){setError('Unable to prepare the PNG. Please try again.');return;}url=URL.createObjectURL(blob);setExportUrl(url);},'image/png'),200);return()=>{active=false;clearTimeout(timer);if(url)URL.revokeObjectURL(url);};},[image,format,label,address,details,name,contact]);
 return <main className="marketing-studio min-h-screen bg-slate-50 p-5 sm:p-10"><div className="mx-auto max-w-6xl"><Link className="text-sm text-ocean-700 underline" href={`/gallery/${token}`}>← Back to gallery</Link><div className="my-6"><p className="text-xs uppercase tracking-widest text-ocean-700">{demo?'Sample marketing kit':'Your marketing kit'}</p><h1 className="mt-2 font-serif text-4xl text-ocean-950">Make your listing stand out.</h1><p className="mt-3 text-sm text-slate-600">Choose a photo, add your details, and download a ready-to-share image. Changes stay in this browser until you leave.</p></div>
 {data?.paywall?.active?<div className="card p-8"><h2 className="font-semibold">Unlock your marketing kit</h2><p className="mt-2">Complete payment in your gallery to use finished photos in templates.</p><Link href={`/gallery/${token}`} className="btn-primary mt-4">Open gallery & pay</Link></div>:data&&data.photos.length>0?<div className="grid gap-8 lg:grid-cols-[340px_1fr]"><div className="card h-fit space-y-4 p-5"><label className="block text-sm">Template<select className="input mt-1 block w-full" value={format} onChange={e=>setFormat(e.target.value as keyof typeof templateSizes)}><option value="square">Social post · 1080 × 1080</option><option value="story">Story · 1080 × 1920</option><option value="flyer">Letter flyer · 2550 × 3300</option></select></label><label className="block text-sm">Photo<select className="input mt-1 block w-full" value={selected} onChange={e=>setSelected(e.target.value)}>{data.photos.map(p=><option key={p.id} value={p.id}>{p.filename}</option>)}</select></label><label className="block text-sm">Occasion<select className="input mt-1 block w-full" value={label} onChange={e=>setLabel(e.target.value)}>{['Just listed','Open house','Just sold'].map(v=><option key={v}>{v}</option>)}</select></label>{[{title:'Address / headline',value:address,set:setAddress,max:100},{title:'Property details',value:details,set:setDetails,max:180},{title:'Agent / brokerage',value:name,set:setName,max:80},{title:'Contact line',value:contact,set:setContact,max:100}].map(f=><label className="block text-sm" key={f.title}>{f.title}<input className="input mt-1 block w-full" value={f.value} maxLength={f.max} onChange={e=>f.set(e.target.value)} /></label>)}{exportUrl?<a className="btn-primary w-full" href={exportUrl} download={`property-${format}.png`}>Download PNG</a>:<button className="btn-primary w-full" disabled>Preparing PNG…</button>}{format==='flyer'&&<button className="btn-secondary w-full" disabled={!image} onClick={()=>window.print()}>Print / Save flyer PDF</button>}<p className="text-xs text-slate-500">Check the preview before exporting. Images are cropped to fill the selected template.</p></div><div className="flex justify-center rounded-2xl bg-slate-200/70 p-4 sm:p-8"><div className="w-full max-w-lg"><canvas ref={canvas} className={`h-auto w-full shadow-xl ${!image?'invisible':''}`} aria-label={`${label} marketing preview for ${address}`} />{!image&&<p className="p-10 text-center text-sm">Loading photo…</p>}</div></div></div>:!error?<p className="p-8">{data?'No finished photos available yet.':'Loading gallery…'}</p>:null}
 {error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}</div></main>;
}
