'use client';
import { useState } from 'react';
import type { z } from 'zod';
import type { propertySchema } from '@/lib/marketing/property';
type Values=z.infer<typeof propertySchema>;
export function PropertyEditor({orderId,initial,slug:initialSlug}:{orderId:string;initial:Values;slug?:string}) {
 const [values,setValues]=useState(initial);const [price,setPrice]=useState(initial.asking_price_cents===null?'':String(initial.asking_price_cents/100));const [slug,setSlug]=useState(initialSlug);const [published,setPublished]=useState(initial.is_published);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const field=(key:keyof Values,value:string)=>setValues(v=>({...v,[key]:value}));
 async function save(publish:boolean) {setBusy(true);setMessage('');try{if(price&&(!/^\d+(\.\d{1,2})?$/.test(price)||Number(price)>1000000000))throw new Error('Enter a valid asking price.');const r=await fetch(`/api/property-sites/${orderId}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,asking_price_cents:price?Math.round(Number(price)*100):null,is_published:publish})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save.');setSlug(d.slug);setPublished(d.is_published);setMessage(publish?'Property website published.':'Draft saved. The website is not public.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 return <div className="grid gap-8 lg:grid-cols-[1fr_320px]"><div className="card space-y-5 p-6"><label className="block text-sm">Headline<input className="input mt-1 block w-full" maxLength={160} value={values.headline} onChange={e=>field('headline',e.target.value)}/></label><label className="block text-sm">Property description<textarea className="input mt-1 block min-h-40 w-full" maxLength={5000} value={values.description} onChange={e=>field('description',e.target.value)}/></label><label className="block text-sm">Asking price (optional, USD)<input className="input mt-1 block" inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} /></label><div className="grid gap-4 sm:grid-cols-2">{([['agent_name','Agent / brokerage'],['agent_phone','Public phone'],['agent_email','Public email']] as const).map(([key,label])=><label key={key} className="text-sm">{label}<input className="input mt-1 block w-full" value={values[key]} onChange={e=>field(key,e.target.value)} /></label>)}</div><p className="text-sm text-slate-500">The published page includes the property address and facts, your text and contact details, and selected finished photos. Unbranded links omit the agent details and Oceano Blue branding.</p><div className="flex flex-wrap gap-3"><button className="btn-secondary" disabled={busy} onClick={()=>save(false)}>{published?'Unpublish & save draft':'Save draft'}</button><button className="btn-primary" disabled={busy} onClick={()=>save(true)}>{busy?'Saving…':published?'Update published website':'Publish website'}</button></div>{message&&<p role="status" className="text-sm">{message}</p>}</div>
 <aside className="card h-fit space-y-4 p-6"><h2 className="font-semibold">{published?'Published':'Draft'}</h2><p className="text-sm text-slate-600">Use Preview to review a saved draft. Publishing requires the order’s media to be unlocked. Unpublishing removes public access; previously loaded photo links expire within 15 minutes.</p>{slug&&<div className="space-y-3 text-sm"><a className="block text-ocean-700 underline" href={`/property/${slug}${published?'':'?preview=1'}`} target="_blank" rel="noreferrer">{published?'Open website':'Preview saved draft'}</a>{published&&<><a className="block text-ocean-700 underline" href={`/property/${slug}?unbranded=1`} target="_blank" rel="noreferrer">Open unbranded website</a><p className="break-all rounded-lg bg-slate-50 p-3">https://app.oceanoblue.net/property/{slug}</p></>}</div>}</aside></div>;
}
