import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireTeamMember } from '@/lib/auth/require-team-member';
import { loadInvoices } from '@/lib/billing/load';
import { periodReport, money } from '@/lib/billing/ledger';
import { reportPeriod } from '@/lib/billing/period';
export const dynamic='force-dynamic';
export default async function Page({searchParams}:{searchParams:Promise<{month?:string}>}) {
  const gate=await requireTeamMember();if(gate.error)notFound();const period=reportPeriod((await searchParams).month);
  const report=periodReport(await loadInvoices(),period.start,period.end);
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold">Revenue reports</h1><p className="mt-1 text-sm text-slate-600">Monthly bookings and recorded payments. Dates use Eastern Time.</p></div><Link href="/dashboard/invoices" className="btn-secondary">Invoices & balances</Link></div>
    <form className="flex flex-wrap items-end gap-3"><label className="text-sm">Month<input className="input mt-1 block" type="month" name="month" defaultValue={period.month}/></label><button className="btn-primary">Update report</button><a href={`/api/reports/billing?month=${period.month}`} className="btn-secondary">Export CSV</a></form>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Booked order value',money(report.booked)],['Recorded collections',money(report.collected)],['New orders',report.orders],['Payments recorded',report.payments]].map(([label,value])=><div className="card p-5" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div>
    <p className="text-sm text-slate-600">Booked value uses non-draft, non-cancelled orders created this month. Collections use the recorded payment date and captured amount, including payments for older orders. These figures do not subtract processor fees or track refunds.</p>
    {(report.missingPrices>0||report.missingPayments>0)&&<p role="status" className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{report.missingPrices} orders have no price and {report.missingPayments} paid orders have no recorded payment amount. Their missing amounts are excluded from totals.</p>}
    <section className="card overflow-x-auto"><h2 className="p-5 font-semibold">By client</h2><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Client</th><th className="p-4 text-right">Booked value</th><th className="p-4 text-right">Recorded collections</th></tr></thead><tbody className="divide-y">{report.clients.map((c,i)=><tr key={i}><td className="p-4">{c.name}{c.missingPayments>0&&<span className="block text-xs text-amber-700">{c.missingPayments} payment amounts missing</span>}</td><td className="p-4 text-right">{money(c.booked)}</td><td className="p-4 text-right">{money(c.collected)}</td></tr>)}</tbody></table>{!report.clients.length&&<p className="p-5 text-sm text-slate-500">No bookings or payments this month.</p>}</section>
    <section className="card overflow-x-auto"><h2 className="p-5 font-semibold">Booked products</h2><p className="px-5 pb-4 text-sm text-slate-500">Item values for orders created this month. Order-level adjustments are excluded; product totals may differ from booked order value.</p><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Product / service</th><th className="p-4 text-right">Quantity</th><th className="p-4 text-right">Booked item value</th></tr></thead><tbody className="divide-y">{report.products.map((p,i)=><tr key={i}><td className="p-4">{p.name}</td><td className="p-4 text-right">{p.quantity}</td><td className="p-4 text-right">{money(p.booked)}</td></tr>)}</tbody></table>{!report.products.length&&<p className="p-5 text-sm text-slate-500">No itemized products this month.</p>}</section>
  </div>;
}
