'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { RoutingProfile } from '@/lib/booking/routing';
export function PhotographerSettings({member,profile,products,blocks,canRoute,canEdit,calendarStatus,self}:{member:{id:string;full_name:string};profile:RoutingProfile|null;products:{id:string;name:string}[];blocks:{id:string;starts_at:string;ends_at:string;reason:string|null}[];canRoute:boolean;canEdit:boolean;calendarStatus:string;self:boolean}) {
  const router=useRouter();const [p,setP]=useState<RoutingProfile>(profile||{team_member_id:member.id,enabled:false,priority:100,product_ids:[],service_zips:[],travel_minutes:30,cross_zip_minutes:45,color:'#0369a1'});
  const [zips,setZips]=useState(p.service_zips.join(', '));const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const [start,setStart]=useState(''),[end,setEnd]=useState(''),[reason,setReason]=useState('');
  async function call(url:string,method:string,body?:unknown) {
    setBusy(true);setMessage('');
    try{const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage('Saved.');router.refresh();return true;}
    catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');return false;}finally{setBusy(false);}
  }
  return <section className="card space-y-5 p-5 sm:p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-semibold">Calendar & routing · {member.full_name}</h3><p className={`mt-1 text-sm ${calendarStatus==='Connected'?'text-emerald-700':'text-amber-800'}`}>{calendarStatus==='Connected'?'Google Calendar connected':'Google Calendar needs attention'} · {calendarStatus}</p></div>{self&&calendarStatus!=='Connected'&&<a className="btn-secondary" href="/api/auth/google/connect">Connect my calendar</a>}</div>
    {calendarStatus!=='Connected'&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Only working hours, app bookings, and time off can be checked until this photographer connects their own Google account.{!self&&' Ask them to open Settings → Availability while signed in.'}</p>}
    {canRoute&&<details><summary className="cursor-pointer text-sm font-semibold">Booking priority, services & travel</summary><div className="mt-5 space-y-5">
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={p.enabled} onChange={e=>setP({...p,enabled:e.target.checked})}/>Offer this photographer in online booking</label>
      <div className="grid gap-4 sm:grid-cols-4"><label className="text-sm">Priority<input type="number" className="input mt-2" min={1} max={1000} value={p.priority} onChange={e=>setP({...p,priority:Number(e.target.value)})}/><span className="text-xs text-slate-500">Lower numbers are offered first.</span></label><label className="text-sm">Travel gap (minutes)<input type="number" className="input mt-2" min={0} max={240} value={p.travel_minutes} onChange={e=>setP({...p,travel_minutes:Number(e.target.value)})}/></label><label className="text-sm">Different ZIP (minutes)<input type="number" className="input mt-2" min={0} max={240} value={p.cross_zip_minutes} onChange={e=>setP({...p,cross_zip_minutes:Number(e.target.value)})}/></label><label className="text-sm">Schedule color<input type="color" className="mt-2 block h-11 w-full rounded border" value={p.color} onChange={e=>setP({...p,color:e.target.value})}/></label></div>
      <p className="text-xs text-slate-500">The largest applicable travel gap wins. ZIP-based buffers are planning allowances, not live driving-time estimates.</p>
      <label className="block text-sm">Service ZIP codes<input className="input mt-2" value={zips} onChange={e=>setZips(e.target.value)} placeholder="29910, 29909, 29928"/><span className="text-xs text-slate-500">Leave empty to cover all areas. Separate five-digit ZIP codes with commas.</span></label>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={p.product_ids===null} onChange={e=>setP({...p,product_ids:e.target.checked?null:[]})}/>Qualified for all services</label>
      {p.product_ids!==null&&<fieldset><legend className="mb-3 text-sm font-medium">Services this photographer can cover</legend><div className="grid max-h-64 gap-3 overflow-y-auto rounded-lg border p-4 sm:grid-cols-2">{products.map(s=><label key={s.id} className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={p.product_ids!.includes(s.id)} onChange={e=>setP({...p,product_ids:e.target.checked?[...p.product_ids!,s.id]:p.product_ids!.filter(id=>id!==s.id)})}/>{s.name}</label>)}</div></fieldset>}
      <button disabled={busy} className="btn-primary" onClick={()=>call('/api/scheduling/profiles','POST',{...p,service_zips:zips.split(/[\s,]+/).filter(Boolean)})}>Save routing</button>
    </div></details>}
    {canEdit&&<details><summary className="cursor-pointer text-sm font-semibold">Time off & blocked time</summary><form className="mt-4 space-y-4" onSubmit={async e=>{e.preventDefault();if(await call('/api/scheduling/time-off','POST',{team_member_id:member.id,starts_at:new Date(start).toISOString(),ends_at:new Date(end).toISOString(),reason})){setStart('');setEnd('');setReason('');}}}>
      <p className="text-sm text-slate-500">Blocks new bookings. Existing shoots remain assigned and should be reviewed separately. Times use your device’s timezone.</p><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">From<input required className="input mt-2" type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="text-sm">Until<input required className="input mt-2" type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><label className="block text-sm">Reason<input className="input mt-2" maxLength={200} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Day off, appointment, unavailable"/></label><button className="btn-secondary" disabled={busy}>Block this time</button>
      <ul className="space-y-2">{blocks.map(b=><li key={b.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-50 p-3 text-sm"><span>{new Date(b.starts_at).toLocaleString()} – {new Date(b.ends_at).toLocaleString()} · {b.reason||'Unavailable'}</span><button type="button" className="text-ocean-700 underline" disabled={busy} onClick={()=>call(`/api/scheduling/time-off?id=${b.id}`,'DELETE')}>Remove block</button></li>)}</ul>
    </form></details>}
    <p role="status" className="text-sm text-slate-600">{message}</p>
  </section>;
}
